### ISSUE TITLE
Bluetooth LE and Arduino

### ISSUE THREAD

**Issue by YichenDuan** [cntgrd/platform#7]
Have an idea about how to send Wi-Fi credential through blue-tooth (https://github.com/IanHarvey/bluepy)
An Arduino backpacking a environmental sensor, build firmware for it, document it.
Print out on screen when sensors connect and output something get from sensor.
Pipenv set up on RPi and my virtual environment
Wi-Fi credential also need to be researched.

**Comment by cykacookie** [comment]
Duplicate to #8
